### Numpy

In [3]:
%pip install numpy
import numpy as np

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
big_list = list(range(100000))
big_array = np.arange(100000)

In [8]:
%timeit [x**2 for x in big_list]

15 ms ± 984 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%timeit big_array **2

112 μs ± 13.4 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [13]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
a = np.array([0, 0, 0, 0])
print(a)

[0 0 0 0]


In [15]:
zero = np.zeros([2,3])
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
one = np.ones((2, 3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print(np.full((2, 3), 7))

[[7 7 7]
 [7 7 7]]


In [19]:
print(np.arange(0, 10, 12))

[0]


In [20]:
print(np.eye(3)) #identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
rng = np.random.default_rng(seed = 42)
print(rng.random((2, 3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [26]:
print(rng.integers(1, 10, size=(3, 3))) #uniform

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [27]:
print(rng.normal(loc = 0, scale = 1, size = 5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


In [29]:
M = np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
print(M.ndim)

2


In [31]:
print(M.shape)

(2, 3)


In [32]:
print(M.size)

6


In [33]:
print(M.dtype)

int64


In [40]:
ints = np.array([1,2,3])

In [41]:
ints.dtype

dtype('int64')

In [38]:
ints = np.array([1,2,3], dtype = np.int32) # change forcely

In [39]:
ints.dtype

dtype('int32')

In [45]:
floats = np.array([1,2,3], dtype = np.float64)
floats.dtype

dtype('float64')

In [47]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
print(M[1,2])

7


In [50]:
M[0]
M[1]

array([5, 6, 7, 8])

In [51]:
print(M[0])

[1 2 3 4]


In [52]:
print(M[1])

[5 6 7 8]


In [53]:
print(M[2])

[ 9 10 11 12]


In [57]:
print(M[:,0])

[1 5 9]


### Vector Operation

In [58]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

In [59]:
print(a)
print(b)

[1 2 3 4]
[10 20 30 40]


In [60]:
print(a+b)

[11 22 33 44]


In [61]:
print(a*b)

[ 10  40  90 160]


In [62]:
a = np.array([1,2,3])
b = 10

In [63]:
print(a+b)

[11 12 13]


In [69]:
a = np.array([[1,2,3],
             [4,5,6]
             ])
a.shape

(2, 3)

In [70]:
b = np.array([10,20,30])
b.shape

(3,)

In [72]:
print(a+b)

[[11 22 33]
 [14 25 36]]


In [73]:
a = np.array([[1,2],
              [3,4]])
a.shape

(2, 2)

In [74]:
b = np.array([10,20,30])
b.shape

(3,)

In [ ]:
print(a+b)